//CommonJS, every file is module (By Default)
//Modules-encapsulated code (only share minimum)
const names=require('./4-names')
const sayHi=require('./5-utils')
const data=require('./6-Alternative-flavour')
console.log(data);
require('./7-mind-grenade')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)
